image: docker:latest

variables:
  PASSWORD: $SERVICE_PRINCIPAL_PASSWORD
  TENANT_ID: $TENANT_ID
  APP_ID: $APP_ID
  SUBSCRIPTION: 3344a922-f246-4f27-a6f1-3c85586f7b99
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/packages/app'
  OUTPUT_PATH: '$APP_PATH/dist'

stages:
  - build
  - deploy
  #- deployWebapp

services:
  - docker:dind

Build & Publish backend image to ACR:
  stage: build
  before_script:
    - echo" ===> Steps to find out the public ip of load balancer"

    ##TODO  - Figure out a way to either hardcode RG and name for public ip resource or find it at runtime programmatically

    #- apt-get install -y azure-cli
    
    #- public_ip=$(az network public-ip show -n kubernetes-a5eb06a72fea24ebfb0a2847afd66c15 -g mc_backstage-poc-rg_backstage-aks-cluster_eastus |jq .ipAddress)
    #- echo $public_ip
    #- sed -i "s/___PUBLIC_IP___/$public_ip/g" app-config.yaml
  script:
    - echo "===> Initiating Docker Build process"
    - docker login backstagepp.azurecr.io -u $APP_ID -p $PASSWORD
    # - docker build . -t backstage
    # - docker tag backstage backstagepp.azurecr.io/backstage:new
    # - echo "====> Initiating Docker image push to ACR"
    # - docker push backstagepp.azurecr.io/backstage:new
  rules:
    - changes:
        - kubernetes
        - terraform
        - pipelines-for-azure
        - ".gitlab-ci.yml"
      when: never
    - when: always


Deploy backend to AKS:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal --username $APP_ID --password $PASSWORD --tenant $TENANT_ID
    # - az aks get-credentials --resource-group backstage-aks_group --name backstage-aks
    # - echo "====> Installing kubectl"
    # - az aks install-cli
    # - echo "====> Creating kubernetes namespace. Calling template file"
    # - kubectl apply -f kubernetes/namespace.yaml
    # - |
    #     if [[ `kubectl -n backstagehttp get secrets |grep "backstage-secrets"` ==  "" ]]; then
    #       echo "=======> Creating secret for backstage"
    #       kubectl -n backstagehttp create secret generic backstage-secrets \
    #       --from-literal=GITHUB_TOKEN=$GITHUB_TOKEN \
    #       --from-literal=AZURE_TECHDOCS_STORAGE_KEY=$AZURE_TECHDOCS_STORAGE_KEY
    #     else
    #       echo "=======> Secret already present"
    #     fi
    # - echo "====> Creating kubernetes backstage depoloyment and service. Calling template file"
    # - kubectl apply -n backstagehttp -f kubernetes/backstage.yaml -f kubernetes/backstage-service.yaml
    # - VAR=$(kubectl -n backstagehttp describe services |grep "LoadBalancer Ingress" |cut -d ":" -f2)
    # - VAR=$(echo ${VAR// /})
    # - echo "====> Access Backstage on - http://$VAR"
  rules:
    - changes:
        - terraform
        - pipelines-for-azure
        - ".gitlab-ci.yml"
      when: never
    - when: always

Deploy frontend to StaticWebApp:
  stage: deploy
  # image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  image: mcr.microsoft.com/appsvc/staticappsclient:stable
  script:
    - pwd
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - node -v
    - yarn -v
    - ls -ltr
    - echo $CI_PROJECT_DIR
    - yarn install
    - cd $APP_PATH
    - pwd
    - yarn build
    - /bin/staticsites/StaticSitesClient upload --verbose --app $OUTPUT_PATH --skipAppBuild true --apiToken $DEPLOYMENT_TOKEN  
    - echo "App deployed successfully."
  rules:
    - changes:
        - terraform
        - pipelines-for-azure
       # - ".gitlab-ci.yml"
        - kubernetes
      when: never
    - when: always
  
